### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by xy0893** [S3r8ph1m/sql-finder#1]
Can a batch check whether there is SQL injection in the URL in the txt text

**Comment by S3r8ph1m** [comment]
> 
> 
> Can a batch check whether there is SQL injection in the URL in the txt text

I am afraid that I'm not quite sure what you are asking, please could you provide more details of your issue/question? 

This script simply does basic SQLi checks in the URL and HTML form fields. 

Here is the command usage:

python3 sql-finder.py -u <Target URL>

**Comment by xy0893** [comment]
![56](https://user-images.githubusercontent.com/80501650/133596535-af7b13b4-0b66-4f4f-bdd9-233284a98f79.png)
Description in the picture

Can sql-finder check whether there is SQL injection in the URL in the 777.txt text on a large scale.

**Comment by S3r8ph1m** [comment]
> ![56](https://user-images.githubusercontent.com/80501650/133596535-af7b13b4-0b66-4f4f-bdd9-233284a98f79.png)
> Description in the picture
> 
> Can sql-finder check whether there is SQL injection in the URL in the 777.txt text on a large scale.

At the moment, I'm afraid it can't. It's in the backlog of things to do. In the meantime other tools like SQLMap have this functionality.

**Comment by xy0893** [comment]
Can you tell me to run sqlmap to check the command characters of the 777.txt text?
--------------
Within the scope of my knowledge, I always think that sqlmap can only run a complete url
For example https://127.0.0.1/en/machine_detail.php?pid=250' and [t] and '1'='1
-----------
The URL I want to check is https://127.0.0.1
